[package]
name = "system-of-linear-equations"
version = "0.1.0"
edition.workspace = true

[dependencies]
nalgebra = "0.33"

[dev-dependencies]
approx = "0.5"
paste = "1.0"
pretty_assertions = "1.4"
rand = "0.9"